### ISSUE TITLE
[NEAR] It gets stuck when I want to connect my Nano X

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1005]
I tried to connect my Nano X, but on Opening Near Application step, it gets stuck. It's displayed the loading. I made a restart, as well went for a "Forgot device". Still the same.

![image](https://user-images.githubusercontent.com/27950955/94824745-097a5f00-040e-11eb-8b66-0931a1ca7913.png)

**Comment by krisboit** [comment]
This one is blocked till near will support bluetooth on their ledger app
