### ISSUE TITLE
[ALL] Touch ID text update

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1010]
As an user I want to have a relevant text when I try to login with my touch ID. Currently we have in description `Authenticate to retrieve secret`. It would be good to use `Please authenticate to proceed`

![image](https://user-images.githubusercontent.com/27950955/94853123-91269480-0433-11eb-97ab-1cbbf6a3c009.png)

**Comment by NovacAndrei** [comment]
![image.png](https://images.zenhubusercontent.com/5dbbee7907187300011ab82c/f1b0f925-faec-4dc5-a073-ad38aea97c3a)
