### ISSUE TITLE
[ZIL] I don't receive gZIL 

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1014]
I made a stake of 349000 ZIL from my Ledger Nano X one day ago and I don't see any gZIL accumulated into my account. https://viewblock.io/zilliqa/address/zil1u469fx6rdfjw8t7z3zw2hxu458xl5plg72unkq?network=testnet

![image](https://user-images.githubusercontent.com/27950955/94892892-9402a300-048e-11eb-87d1-f07dc551b2ed.png)

**Comment by georgeburduhos** [comment]
@i3uRi try to make a Claim reward - from what i saw the gZil becomes available only if you claim rewards

**Comment by georgeburduhos** [comment]
Not a bug - this it the behaivour
