### ISSUE TITLE
[ZIL] Add expandable Claim Now widder on Account Page

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1016]
As an user I want to see all Claim Now widgets on Account Page so that it would be easier to claim rewards and receive back gZIL.

- Add Claim Now expandable widget
- On tap it should expand and display all widgets
- No collapse is required for now
- No deed to remember its state. Each time when 
user enters the Account page it the widget should
be collapsed.

Check the files in Figma: https://www.figma.com/file/Tg9SEyEEzZ8L565ZzEwQRB/Moonlet-3.0-Figma-iOS-UI-kit-2.0?node-id=11075%3A262862

Check this video: https://discordapp.com/channels/568167510961029153/675303250429345822/761500914720178206

**Comment by i3uRi** [comment]
@georgeburduhos I'm not able to see Claim widgets anymore on my Token Page, even if I have aroud 300 ZIL as reward.

![image](https://user-images.githubusercontent.com/27950955/95332995-d6741780-08b4-11eb-8679-23dbaa65b1f6.png)

**Comment by georgeburduhos** [comment]
@i3uRi i will mark this as done even if the collapsable is not completed. Let't do this next week :)
