### ISSUE TITLE
[ZIL] Moonlet appears to add a "zilliqa://" suffix by default to the zil address causing invalid address error

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1031]
Noticed when testing zilpay:

> select zil > receive > deposit zil to zilpay > using Moonlet to scan qr code > Moonlet appears to add a "zilliqa://" suffix by default to the zil address causing invalid address error (which can be manually backspaced to solve currently.

![image.png](https://images.zenhubusercontent.com/5b72918402b9fd36cfbf71b4/051a3206-9664-4975-a4c7-e79058be9d5c)

**Comment by standreinmcp** [comment]
Blocker: QR Code doesn't work.

**Comment by i3uRi** [comment]
What do you mean? @standreinmcp
