### ISSUE TITLE
[LEDGER] Issues on new flow

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1067]
Prerequisites:
- iOS
- Ledger Nano X
- Zilliqa

**Issue 1 - Back button on Claim flow doesn't work**

Current behaviour:
- On tap, the Back button from Processing page doesn't work

Expected behaviour:
- On tap, the Back button should return the user from where it initiated the Claim operation, either Token Page or Node Page

**Issue 2 - Transaction has failed on Claim flow and I didn't signed it**

Current behaviour:
- After you tap on _Sign 1st transaction_ it starts the connectivity flow and once it reaches the Review transaction step, it triggers below error, before even signing the transaction

![image.png](https://images.zenhubusercontent.com/5b72918402b9fd36cfbf71b4/26fae2cb-49da-4ced-95e1-b391d2c43b7b)

Expected behaviour:
- After you tap on _Sign 1st transaction_ it should starts the connectivity flow and once it reaches the Review transaction it should wait for transaction to be signed from Ledger.

**Issue 3 - Transaction has failed on Send flow and I didn't signed it**

Current behaviour:
- After you tap on Send and go through all steps from the flow and Ledger connectivity, once  t reaches the Review transaction step, it triggers below error, before even signing the transaction.

![image.png](https://images.zenhubusercontent.com/5b72918402b9fd36cfbf71b4/7b2f9ae8-c952-4da2-8527-d6d727db54be)

**Comment by i3uRi** [comment]
Issue 4 - On Android during the Connect or Sign transaction flow the Retry screen is displayed several times for 1 second. it flickers @georgeburduhos 

Current behaviour:

On Android during the Connect or Sign transaction flow the Retry screen is displayed several times for 1 second. it flickers

Expected behaviour:

On Android during the Connect or Sign transaction flow if everything goes ok the Retry screen should not be reveald.

**Comment by i3uRi** [comment]
Issue 5 - On Android during the Sign transaction flow the Searching screen is displayed partially @georgeburduhos

Current behaviour:

On Android during the Sign transaction flow the Searching screen is displayed partially, like here: ![image](https://user-images.githubusercontent.com/27950955/95475256-b1ec6e00-098e-11eb-9e46-7d72f74de961.png)

Expected behaviour:

On Android during the Sign transaction flow the Searching screen should be displayed fully.

**Comment by i3uRi** [comment]
**Issue 6 - Empty screen after I had to retry and Connect again**

Current behaviour:

I received the Retry screen since it took a lot of time to open the Ledger. I clicked on Retry and on Connect again I had a black screen as below:
![image](https://user-images.githubusercontent.com/27950955/95478682-866b8280-0992-11eb-86dd-5ccf164ba2e0.png)


Expected behaviour:

On retry and Connect again it should bring the user on the normal flow.

**Comment by i3uRi** [comment]
Issue 7 - On Processing screen, the last one, the icon doesn't spin @georgeburduhos

Current behaviour:
On Processing screen, last one, the icon doesn't spin.

Expected behaviour:
On Processing screen, last one, the icon should spin.

![Uploading image.png…]()

**Comment by i3uRi** [comment]
**Issue 8 - After you sign a transaction on Send flow it doesn't open the Transaction tab on Token Page @georgeburduhos** 

Current behaviour:
After transaction is signed on Send flow it opens Account tab

Expected behaviour:
After transaction is signed on Send flow it should open Transaction tab

**Comment by georgeburduhos** [comment]
@i3uRi issues 1 2 3 7 and 8 are ready to be tested in 863 build and above
