### ISSUE TITLE
[NEAR] I'm not able to see my summary balances and validators on My Stakes tab

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1073]
Current behaviour:

After I have recovered a lockup account, I was not able to see my staked balances on Summary widget and the validators on My Stakes tab. I had to recover one more time that account to make it work.

Expected behaviour:

After I recover a lockup account I should be able to see immediately my staked balances on Summary widget and the validators on My Stakes tab.

**Comment by NovacAndrei** [comment]
@i3uRi Please try again now
