### ISSUE TITLE
[ALL] Update Processing page title and description

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1081]
Current behaviour: The current title is **Processing**. The current description is **Please sign each transaction from your Ledger and wait while is being processed** for Ledger and **Please wait while each transaction is being processed** for HD Wallet.

Expected behaviour: The title should be **Sign transaction(s)**. The description should be **Please sign each transaction from your Ledger and wait while is being broadcasted to the blockchain network** for Ledger and **Please sign all transactions and wait while are being broadcasted to the blockchain network** for HD Wallet

**Comment by i3uRi** [comment]
We need an update here @georgeburduhos . I removed that "wait" verb.

Current behaviour: The description are **Please sign each transaction from your Ledger and wait while is being broadcasted to the blockchain network** for Ledger and **Please sign all transactions and wait while are being broadcasted to the blockchain network** for HD Wallet

Expected behaviour: The descriptions should be **Please sign each transaction from your Ledger in order to start broadcasting to the blockchain network** for Ledger and **Please sign all transactions in order to start broadcasting to the blockchain network** for HD Wallet

**Comment by i3uRi** [comment]
@krisboit @georgeburduhos @standreinmcp I had a comment above and I believe you missed this change. The text is still a bit misleading and we need to change it.

**Comment by georgeburduhos** [comment]
Changed. Available in the next builds
