### ISSUE TITLE
[ALL] Disable notification for this GO LIVE

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1083]
We need to disable notifications. Currently even if it's a hidden feature notifications are sent to test users. We need to make sure we remove it from GO LIVE scope, 14th of Oct

**Comment by NovacAndrei** [comment]
@i3uRi  This was already done. Notifications is now under `DEV_TOOLS` throttle.

In `DEV_TOOLS` you can see:
1. Copy Paste
2. Generate Wallet
3. Notification Center
...

In order for you to test this, tell me to remove your deviceId from firebase.
