### ISSUE TITLE
Bug Process transactions - sign all transactions

### ISSUE THREAD

**Issue by NovacAndrei** [Moonlet/wallet-app#1085]
1. Press on `Sign all transactions` button
2. Start broadcasting
3. You can still press `Sign all transactions` button and sign again the transactions

![image.png](https://images.zenhubusercontent.com/5dbbee7907187300011ab82c/a2123c1a-88ea-47d8-b24c-dbda3a331e61)

**Comment by i3uRi** [comment]
Il looks that the button is still there in the first second or two, not disabled, but not clickable. Therefore is a good workaround since the user is not able to tap twice the **Sign all transaction** button
