### ISSUE TITLE
[ZIL] Unstake doesn't work

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1127]
Current behaviour: If you want to Unstake on HD wallet it doesn't work. Only the Claim transaction is broadcasted and confirmed. The Unstake one has an error:

https://viewblock.io/zilliqa/tx/522bbfdb1cc27f45f72eece559378966b0090cdf9756f4b1b789716efebc40cb?network=testnet
https://viewblock.io/zilliqa/tx/de0a69b5173ca1a3ab4c2ca3c65c4dee77dac897d8ad9a3a40d62d9070831278?network=testnet

Expected behaviour: If you want to Unstake it should work and both Claim and Unstake should be broadcasted and confirmed.

**Comment by georgeburduhos** [comment]
@krisboit  - this is ok now?

**Comment by i3uRi** [comment]
@georgeburduhos I made an Unstake with success from both HD and Ledger. I'll close it. Just that we have a new issue on this flow that I raised it here: https://github.com/Moonlet/wallet-app/issues/1155
