### ISSUE TITLE
[ZIL] All Claim widgets are displayed if one Reward balance is above the 100 ZIL threshold 

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1130]
Current behaviour: If only one Reward balance is above the 100 ZIL threshold, then all Claim widgets are displayed on Token Page.

Expected behaviour: Only one Reward balances that are above the 100 ZIL threshold should be displayed on Token Page.

**Comment by georgeburduhos** [comment]
@i3uRi its ok. on testnet it was 0.1 . I just changed to 5 Zil treshold in order to be easier to test the correct behaviour 
On mainnet is set to 100 ZIL
