### ISSUE TITLE
[ZIL] Rewards are not coming

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1136]
Current behaviour: Rewards are not coming at the end of each cycle/epoch

Expected behaviour: Rewards should come in order to be able to claim them.

**Comment by georgeburduhos** [comment]
@i3uRi  - i tested today with account 4 and i saw rewards. This might be from the fix that i made earlier on rewards calculator on monorepo. This impacted the unstake as well. Please confirm
