### ISSUE TITLE
[NEAR] Balance doesn't update after a Stake or Unstake is performed from a lockup contract account 

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1138]
Current behaviour: If you make a Stake or Quick Stake or Unstake from a lockup contract account, the balances on Summary doesn't update on both Dashboard and Token Page. As well on Stake Now banner and Node card.

Expected behaviour: If you make a Stake or Quick Stake or Unstake from a lockup contract account, all balances should reflect the current status of your account.

**Comment by i3uRi** [comment]
@NovacAndrei I noticed that in the end the balance updates just that it takes more time to update the balance on lockup accounts vs on a normal account. Is this a known behaviour?

**Comment by NovacAndrei** [comment]
@i3uRi Please test again this, because Tibi made some changes on API with our cache. 
It should be fixed now. 
Otherwise let me know and I'll check again.
