### ISSUE TITLE
[NEAR] Unstake doesn't work on Mainnet. It works on Testnet

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#1163]
Current behaviour: If you want to Unstake funds on Mainnet, it doesn't work. I had the following errors:
https://explorer.mainnet.near.org/transactions/6xm1qnMvjSdoEG1YT6zd1bBqU1YUXD59ha26go5VBYaT
https://explorer.mainnet.near.org/transactions/9dwdMSXm4JmKYih8EoB5DZgAUFFJu3Fq21jv9y6oZG2E

Expected behaviour: Unstake should go through.

**Comment by NovacAndrei** [comment]
@i3uRi Please check again this on the latest build.
