### ISSUE TITLE
Create Flow. Don't forget to remove the confirmation words

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#511]
As an owner I want to have the confirmation words from Create flow removed so that will not be available for users. This feature was used during extensive testing of the flow, but it should be removed.

![Confirmation words.png](https://images.zenhubusercontent.com/5b72918402b9fd36cfbf71b4/5c437061-074c-46e5-b2d3-58ca2457a35a)

**Comment by NovacAndrei** [comment]
This feature is only available for developers (it's activated using the Device ID via Firebase).
