### ISSUE TITLE
Outbount, Inbound and Failed transaction notifications should be relevant

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#595]
As an user I want to receive relevant notifications on my mobile when an inbound, outbound or failed transaction is confirmed so that it would be informed about all transactions within my wallet. As well when users taps on a notification, the relevant account page should be opened.

Therefore, we should have the following notification titles:

1. **Transaction sent** for outbound transactions
2. **Transaction received** for inbound transactions
3. **Transaction failed** for failed transactions

Example below:
```  
Transaction sent
110 ZIL sent to the following address: zil1f...lsd7t

```

```  
Transaction received
10 ZIL received from the following address: zil1f...lsd7t

```

```  
Transaction failed
10 ZIL failed to be sent to the following address: zil1f...lsd7t

```

This is how it should look:
![Lock Screen – Notification 02](https://user-images.githubusercontent.com/27950955/81404367-fa80d080-913d-11ea-90a1-86d56234d9db.png)

**Comment by krisboit** [comment]
@i3uRi we should keep the status of the transaction, there is a possibility that a transaction fails.

**Comment by krisboit** [comment]
maybe SENT SUCCESSFULY and SEND FAILED, for RECEIVE something simmilar.
