### ISSUE TITLE
Changing `Transfer` eventname to `TransferSuccess`

### ISSUE THREAD

**Issue by evesnow91** [Moonlet/wallet-app#719]
To align with the changes due to Quantstamp audit:
https://github.com/Zilliqa/ZRC/pull/53

https://github.com/Moonlet/wallet-app/blob/d2afc6c09d03bf349c8934a13abccf06999824a4/src/core/blockchain/zilliqa/client-utils.ts#L41

**Comment by krisboit** [comment]
@evesnow91 We add a fix for this in #720 it will be available with apps v1.4.1.617 or greater.
I will close this issue, please reopen if you have concerns
