### ISSUE TITLE
Wallet is not switched if i make a transaction on extension

### ISSUE THREAD

**Issue by georgeburduhos** [Moonlet/wallet-app#733]
Steps:

1. Create 2 wallets - in my case i had HD wallet and ledger
2. Set active wallet on both to ledger
3. Switch from extension to hd wallet
4. Initiate a transaction
5. Confirm signing after push is received on mobile.

Result - it asks to confirm the transaction on ledger but is should sign a transaction since it comes from hd wallet

**Comment by krisboit** [comment]
@georgeburduhos did you have the same mnemonic on both HD wallet and ledger ?

**Comment by krisboit** [comment]
i may found the problem, on send screen we should send the walletID (https://github.com/Moonlet/wallet-app/blob/master/src/screens/send/send.tsx#L154). Right now walletName is sent, but it's just for display purpose, we should send wallet id and use it to sign from the correct wallet.

**Comment by georgeburduhos** [comment]
@krisboit  yes it was the same mnemonic on both HD wallet and ledger
