### ISSUE TITLE
Small screens display issues

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#740]
As an user I want to  be able to have the screen displayed properly on small screen devices so that I will be able to use the app.

Below screen has been sent by an user with a low screen device:

![image.png](https://images.zenhubusercontent.com/5b72918402b9fd36cfbf71b4/45d27c88-af30-4ded-96b6-6bb7608145eb)

**Comment by krisboit** [comment]
This is not a small screen issue, it's replicable on big screens also if you change font size on os level.

We need to do some research on how to handle this

**Comment by krisboit** [comment]
@NovacAndrei it seems there is a way to detect font scale, so we could optimise our normalize function
see: https://github.com/react-native-community/react-native-device-info#getfontscale
