### ISSUE TITLE
Basic send form

### ISSUE THREAD

**Issue by krisboit** [Moonlet/wallet-app#86]
- create the screen
- add it to navigation
- fix send button from account page
- implement the form, just the basics, recipient, amount, and no fee field
- make the interaction
- implement address validation for:
  - zil - verify that the address is a bech32 valid address
  - eth - verify that the address has the correct length
  - near - we need to do some research here, just implement a dummy function that returns TRUE

**Comment by krisboit** [comment]
@i3uRi For ethereum, right now on the extension, we check if the address is a valid checksummed address, but this is a little bit confusing for users as they copy the addres from various places that don't display the checksummed address.
I propose to check only the length and that the characters are valid hex chars, and if the address is not checksum valid to display a warning bellow the recipient text input. (Ex: we can't confirm this address is correct, please use a checksum valid address. More info about checksum valid addresses.)

**Comment by i3uRi** [comment]
Sound good.

**Comment by krisboit** [comment]
@georgeburduhos we can exclude near from here, as the account creation is very different, we need some research here.
