### ISSUE TITLE
Send screen own accounts transfer

### ISSUE THREAD

**Issue by krisboit** [Moonlet/wallet-app#89]
- by choosing "transfer between my accounts" user should see a list with all his accounts

**Comment by krisboit** [comment]
@i3uRi In figma on you displayed only the accounts from current wallet, but we can display all the accounts, first the current wallet then the other wallets if there are any.

**Comment by i3uRi** [comment]
Let's keep it simple at this stage, namely to have only the accounts from current wallet, request which is coming from community for our existing extension. If we need more, we shall tackle at a later stage. @krisboit

**Comment by krisboit** [comment]
@i3uRi i agree
