### ISSUE TITLE
Validators Tab - Empty state

### ISSUE THREAD

**Issue by NovacAndrei** [Moonlet/wallet-app#930]
Fix Design for empty state

![image.png](https://images.zenhubusercontent.com/5dbbee7907187300011ab82c/dfb18df5-6854-4ceb-9f79-ee985cf4ed94)

**Comment by standreinmcp** [comment]
@i3uRi o sa am nevoie sa stiu ce sa pun aici, in loc de lista goala

**Comment by i3uRi** [comment]
![image.png](https://images.zenhubusercontent.com/5b72918402b9fd36cfbf71b4/193ef3c9-cce7-481b-bdaf-41409007842c)
