### ISSUE TITLE
The default order of cards on ZIL dashboard should be: ZIL, gZIL, XSGD

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#952]
As an user I want to have the following order of the tokens on ZIL dashboard, so that it would be much easier to check and manage ZIL and GZIL.

Order: ZIL, gZIL, XSGD

**Comment by georgeburduhos** [comment]
@standreinmcp 

```
   autoAddedTokensSymbols: {
        '1': {
            XSGD: XSGD_MAINNET,
            gZIL: GZIL_MAINNET
        },
        '333': {
            gZIL: GZIL_TESTNET
        }
    },
```

Aici o sa te ajute sa faci modificarile - ordinea

**Comment by standreinmcp** [comment]
@georgeburduhos doar ordinea lor: move gZil to be first?

**Comment by georgeburduhos** [comment]
Something like that. should work, need to test it to confirm.

**Comment by standreinmcp** [comment]
Still the same. The order is zil xsgd and then gzil. Looking further into this
![Screen Shot 2020-09-28 at 3.09.37 PM.png](https://images.zenhubusercontent.com/5f154fcddca802e7b0a36ef8/ff8d6486-403a-46ca-bc87-40a85e79d224)
