### ISSUE TITLE
Calculate Avg.Reward and Reward for both Account Page and Node Page

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#954]
As an user I want to know what is the average reward and reward rate on both Account Page and Node Page

- Calculate Avg.Reward on Account Page. Take into account the share per Node and each Node Commission or Fee.
- Calculate Reward per Node Page. Take into account Node Commission or Fee when you'll do the math.

**Comment by i3uRi** [comment]
Check here some examples about Weighted Average https://www.investopedia.com/terms/w/weightedaverage.asp. In our case, for computing Avg. Reward we need to take into account the Weight, which in this case is the % delegated to a specific node. For instance:

Bob delegated 1000 units to Node 1 and 3000 units to Node 2. The weight in this case is 0.25 for Node 1 and 0.75 for Node 2. As well, in order to compute the Reward for each node, you need to take into account ZIliqa Reward minus Node Fee. Therefore, the final formula might look like this: ((ZIliqa Reward - Node 1 Fee)x Node 1 Weight)+((ZIliqa Reward - Node 2 Fee)x Node 2 Weight). Hope it makes sense. @georgeburduhos

**Comment by i3uRi** [comment]
@georgeburduhos Was this solved?

**Comment by georgeburduhos** [comment]
Nope. Its an api thing and we left it for next week
