### ISSUE TITLE
Display all available nodes on Quick Stake flow and select all of them by default. Remove the - and + button form the top of the page.

### ISSUE THREAD

**Issue by i3uRi** [Moonlet/wallet-app#956]
As an user I want to have all the nodes displayed on Quick Stake flow and selected by default so that I can put my eggs in more than one or two baskets.

- Display all available Zilliqa nodes
- Select all of them by default
- Remove the - and  + button

**Comment by NovacAndrei** [comment]
You can do also this for Near, currently we have only the Moonlet validator.
