### ISSUE TITLE
Don’t ask for for password in case of Ledger Connect

### ISSUE THREAD

**Issue by georgeburduhos** [Moonlet/wallet-app#996]
On ledger connect flow there should be no PIN logins. The exception is when the user sets the ledger wallet as the first and only wallet, in this case we have to create a PIN.

**Comment by krisboit** [comment]
@georgeburduhos We don't really need to check if we have a pin already set, we can check if there are any wallets in redux. If there is at least one wallet available then the user had already set a PIN.
